-// LANGUAGE: Java
-// AUTHOR: Vivek Paul
-// GITHUB: https://github.com/frankfalcon
-
-public class hello_world_frankfalcon {
-
-    public static void main(String[] args) {
-        System.out.println("Hello, world!");
-    }
-
-}
